-- MySQL Script generated by MySQL Workbench
-- Thu Feb  2 15:14:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Kickmouse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Kickmouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Kickmouse` DEFAULT CHARACTER SET utf8 ;
USE `Kickmouse` ;

-- -----------------------------------------------------
-- Table `Kickmouse`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kickmouse`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(124) NOT NULL,
  `password` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kickmouse`.`score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kickmouse`.`score` (
  `idscore` INT NOT NULL AUTO_INCREMENT,
  `number_score` INT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `average` VARCHAR(24) NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idscore`, `user_iduser`),
  INDEX `fk_score_user_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_score_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `Kickmouse`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
